spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

tournament-client:
  enabled: false
  url: ""
